### ISSUE TITLE
Is the save structure doc in this repo newest for 1.0 version?

### ISSUE THREAD

**Issue by Haosonn** [moritz-h/satisfactory-3d-map#7]
I used the following structure provided. All good before `SessionVisibility`, but it turns out that something gets wrong at `SessionVisibility` with value `-102` and afterward (EditorObjectVersion=40) . 
```
+----------+-----------------------+
| int32    | SaveHeaderVersion     |
| int32    | SaveVersion           |
| int32    | BuildVersion          |
| FString  | MapName               |
| FString  | MapOptions            |
| FString  | SessionName           |
| int32    | PlayDurationSeconds   |
| int64    | SaveDateTime          |
| int8     | SessionVisibility     |
| int32    | EditorObjectVersion   |
| FString  | ModMetadata           |
| bool     | IsModdedSave          |
| FString  | SaveIdentifier        |
| bool     | IsPartitionedWorld    |
| FMD5Hash | SaveDataHash          |
| bool     | IsCreativeModeEnabled |
+----------+-----------------------+
```

I also tried referencing `FGSaveManagerInterface.h` of the newest version from my 1.0 game dir. There may also be something wrong (EditorObjectVersion = 10394) 
```

	int32 SaveVersion;
	int32 BuildVersion;
	FString SaveName;
	ESaveLocationInfo SaveLocationInfo;
	FString MapName;
	FString MapOptions;
	FString SessionName;
	int32 PlayDurationSeconds;
	FDateTime SaveDateTime;
	int32 EditorObjectVersion;
	FString ModMetadata;
	bool IsModdedSave;
	FMD5Hash SaveDataHash;
	bool IsEditedSave;
	FString SaveIdentifier;
	bool IsPartitionedWorld;
	bool IsCreativeModeEnabled;
```
So which one is correct with the current 1.0 version?

**Comment by Haosonn** [comment]
I fixed it by reading bool vars as int(4 bytes). 
But after `IsCreativeModeEnabled`, there are 3 bytes of full 0 before `0x9E2A83C1`, is that right?

**Comment by moritz-h** [comment]
Yes bools are 4 byte. Unreal serializes them as uint32 (see https://github.com/moritz-h/satisfactory-3d-map/blob/v0.7.0/docs/SATISFACTORY_SAVE.md#basic-types).

The documented header should also be correct for 1.0. It did not change since Update 8. The header only ever changes when SaveHeaderVersion changes, so you may validate if the value is still 13.

I can observe EditorObjectVerion is 40 for the 1.0 saves I have seen so far. You can download the 3d map tool from the Releases page (https://github.com/moritz-h/satisfactory-3d-map/releases) and try reading you save file. The save header will be printed into the log file, so you may can compare to your parsing results.

Overall the documentation should mostly be valid for 1.0. The low level structure did not change that much from Update 8. Changes in 1.0 saves I have seen so far are:
- Missing Struct names and missing Map types
- The InventoryItem struct has changes
- Many buildings are now stored in the lightweight building subsystem which is not parsed yet and not documented (That's the missing "Class-Specific Binary Data" section in the docs).
