### ISSUE TITLE
model tessellation level

### ISSUE THREAD

**Issue by SgT012003** [moritz-h/satisfactory-3d-map#8]
## Unity and Unreal Parsing Objects Problem

when you parse the LOD Meshs you need to parse the model tessellations level to process the ground level and upper lever separately

![image](https://github.com/user-attachments/assets/3d60717d-2786-496d-859c-9f3008741fc5)
this is an example.

In game this terrain is above the ground forming like a bridge.

**Comment by moritz-h** [comment]
That is not releated to LODs. The image you showed is a simple height map representation from a low res height map which is within the game files (probably used by the fog of war calculations in the ingame map).
With this it's not possible to have multiple levels.

Because this mode is limited there was the alternative LOD representation in the tool, but this broke with the Unreal 5 update of the game and has not been updated since then yet. Therefore, currently only the fallback to that simple height map world view is working.
I have it on my to do list to update the LOD parsing when there is time.

So the issue is that there is currently no LOD parsing at all, but this very specific report is not the issue.

**Comment by moritz-h** [comment]
I added #10 to keep track of the missing LOD parsing support.
